// @generated by @modern-js/create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'shell' as const;

export const ultramodernRouteMetadata = [
  {
    canonicalPath: '/',
    descriptionKey: 'shell.seo.description',
    id: 'shell-home',
    indexable: false,
    localisedPaths: {
      cs: '/',
      en: '/',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'shell.title',
  },
  {
    canonicalPath: '/tractors',
    descriptionKey: 'shell.seo.description',
    id: 'shell-tractors',
    indexable: false,
    localisedPaths: {
      cs: '/traktory',
      en: '/tractors',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'shell.routes.listing',
  },
  {
    canonicalPath: '/stores',
    descriptionKey: 'shell.seo.description',
    id: 'shell-stores',
    indexable: false,
    localisedPaths: {
      cs: '/prodejci',
      en: '/stores',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'shell.routes.storePicker',
  },
  {
    canonicalPath: '/tractors/:slug',
    descriptionKey: 'shell.seo.description',
    id: 'shell-product-detail',
    indexable: false,
    localisedPaths: {
      cs: '/traktory/:slug',
      en: '/tractors/:slug',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'shell.routes.productDetail',
  },
  {
    canonicalPath: '/cart',
    descriptionKey: 'shell.seo.description',
    id: 'shell-cart',
    indexable: false,
    localisedPaths: {
      cs: '/kosik',
      en: '/cart',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'shell.routes.cart',
  },
  {
    canonicalPath: '/checkout',
    descriptionKey: 'shell.seo.description',
    id: 'shell-checkout',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna',
      en: '/checkout',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.checkout',
  },
  {
    canonicalPath: '/checkout/thank-you',
    descriptionKey: 'shell.seo.description',
    id: 'shell-checkout-thank-you-parent',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna/dekujeme',
      en: '/checkout/thank-you',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.thankYou',
  },
  {
    canonicalPath: '/checkout/thank-you/:orderId?',
    descriptionKey: 'shell.seo.description',
    id: 'shell-checkout-thank-you',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna/dekujeme/:orderId?',
      en: '/checkout/thank-you/:orderId?',
    },
    mfBoundaryId: 'shellSuperApp',
    namespace: 'shell',
    ownerAppId: 'shell-super-app',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.thankYou',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/cart': {
    cs: '/kosik',
    en: '/cart',
  },
  '/checkout': {
    cs: '/pokladna',
    en: '/checkout',
  },
  '/checkout/thank-you': {
    cs: '/pokladna/dekujeme',
    en: '/checkout/thank-you',
  },
  '/checkout/thank-you/:orderId?': {
    cs: '/pokladna/dekujeme/:orderId?',
    en: '/checkout/thank-you/:orderId?',
  },
  '/kosik': {
    cs: '/kosik',
    en: '/cart',
  },
  '/pokladna': {
    cs: '/pokladna',
    en: '/checkout',
  },
  '/pokladna/dekujeme': {
    cs: '/pokladna/dekujeme',
    en: '/checkout/thank-you',
  },
  '/pokladna/dekujeme/:orderId?': {
    cs: '/pokladna/dekujeme/:orderId?',
    en: '/checkout/thank-you/:orderId?',
  },
  '/prodejci': {
    cs: '/prodejci',
    en: '/stores',
  },
  '/stores': {
    cs: '/prodejci',
    en: '/stores',
  },
  '/tractors': {
    cs: '/traktory',
    en: '/tractors',
  },
  '/tractors/:slug': {
    cs: '/traktory/:slug',
    en: '/tractors/:slug',
  },
  '/traktory': {
    cs: '/traktory',
    en: '/tractors',
  },
  '/traktory/:slug': {
    cs: '/traktory/:slug',
    en: '/tractors/:slug',
  },
} as const;

export const ultramodernPublicRoutes = [] as const;

export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
