// @generated by @modern-js/create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'decide' as const;

export const ultramodernRouteMetadata = [
  {
    canonicalPath: '/',
    descriptionKey: 'decide.seo.description',
    id: 'decide-home',
    indexable: false,
    localisedPaths: {
      cs: '/',
      en: '/',
    },
    mfBoundaryId: 'verticalDecide',
    namespace: 'decide',
    ownerAppId: 'decide',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'decide.title',
  },
  {
    canonicalPath: '/tractors',
    descriptionKey: 'decide.seo.description',
    id: 'decide-listing-parent',
    indexable: false,
    localisedPaths: {
      cs: '/traktory',
      en: '/tractors',
    },
    mfBoundaryId: 'verticalDecide',
    namespace: 'decide',
    ownerAppId: 'decide',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'decide.routes.listing',
  },
  {
    canonicalPath: '/tractors/:slug',
    descriptionKey: 'decide.seo.description',
    id: 'decide-product-detail',
    indexable: false,
    localisedPaths: {
      cs: '/traktory/:slug',
      en: '/tractors/:slug',
    },
    mfBoundaryId: 'verticalDecide',
    namespace: 'decide',
    ownerAppId: 'decide',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'decide.routes.productDetail',
  },
  {
    canonicalPath: '/unavailable',
    descriptionKey: 'decide.seo.description',
    id: 'decide-unavailable',
    indexable: false,
    localisedPaths: {
      cs: '/nedostupne',
      en: '/unavailable',
    },
    mfBoundaryId: 'verticalDecide',
    namespace: 'decide',
    ownerAppId: 'decide',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'decide.routes.unavailable',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/nedostupne': {
    cs: '/nedostupne',
    en: '/unavailable',
  },
  '/tractors': {
    cs: '/traktory',
    en: '/tractors',
  },
  '/tractors/:slug': {
    cs: '/traktory/:slug',
    en: '/tractors/:slug',
  },
  '/traktory': {
    cs: '/traktory',
    en: '/tractors',
  },
  '/traktory/:slug': {
    cs: '/traktory/:slug',
    en: '/tractors/:slug',
  },
  '/unavailable': {
    cs: '/nedostupne',
    en: '/unavailable',
  },
} as const;

export const ultramodernPublicRoutes = [] as const;

export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
