// @generated by @modern-js/create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'explore' as const;

export const ultramodernRouteMetadata = [
  {
    canonicalPath: '/',
    descriptionKey: 'explore.seo.description',
    id: 'explore-home',
    indexable: false,
    localisedPaths: {
      cs: '/',
      en: '/',
    },
    mfBoundaryId: 'verticalExplore',
    namespace: 'explore',
    ownerAppId: 'explore',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'explore.title',
  },
  {
    canonicalPath: '/tractors',
    descriptionKey: 'explore.seo.description',
    id: 'explore-listing',
    indexable: false,
    localisedPaths: {
      cs: '/traktory',
      en: '/tractors',
    },
    mfBoundaryId: 'verticalExplore',
    namespace: 'explore',
    ownerAppId: 'explore',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'explore.routes.listing',
  },
  {
    canonicalPath: '/stores',
    descriptionKey: 'explore.seo.description',
    id: 'explore-store-picker',
    indexable: false,
    localisedPaths: {
      cs: '/prodejci',
      en: '/stores',
    },
    mfBoundaryId: 'verticalExplore',
    namespace: 'explore',
    ownerAppId: 'explore',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'explore.routes.storePicker',
  },
  {
    canonicalPath: '/unavailable',
    descriptionKey: 'explore.seo.description',
    id: 'explore-unavailable',
    indexable: false,
    localisedPaths: {
      cs: '/nedostupne',
      en: '/unavailable',
    },
    mfBoundaryId: 'verticalExplore',
    namespace: 'explore',
    ownerAppId: 'explore',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'explore.routes.unavailable',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/stores': {
    cs: '/prodejci',
    en: '/stores',
  },
  '/tractors': {
    cs: '/traktory',
    en: '/tractors',
  },
  '/unavailable': {
    cs: '/nedostupne',
    en: '/unavailable',
  },
} as const;

export const ultramodernPublicRoutes = [] as const;

export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
