import { defineRuntimeConfig } from '@modern-js/runtime';
import { createInstance } from 'i18next';
import { ultramodernRouteNamespace } from './routes/ultramodern-route-metadata';

const i18nInstance = createInstance();

export default defineRuntimeConfig({
  i18n: {
    i18nInstance,
    initOptions: {
      defaultNS: ultramodernRouteNamespace,
      fallbackLng: 'en',
      interpolation: {
        escapeValue: false,
      },
      ns: [ultramodernRouteNamespace, 'translation'],
      resources: {
        cs: {
          shell: {
            checkout: {
              actions: {
                addToCart: 'Přidat do košíku',
                checkout: 'Pokladna',
                continueShopping: 'Pokračovat v nákupu',
                remove: 'Odebrat',
                viewCart: 'Zobrazit košík',
              },
              cart: {
                empty: 'Košík je prázdný.',
                title: 'Košík',
                total: 'Celkem',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              product: {
                stockShipping: '8 skladem, doprava zdarma',
              },
              role: 'pokladna',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              title: 'Pokladní remote',
            },
            decide: {
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              product: {
                availability: 'Dostupnost',
                eyebrow: 'Detail stroje',
                features: {
                  comfort: 'Ergonomický návrh zaměřený na pohodlí a efektivitu obsluhy',
                  landscapes: 'Optimalizovaný pro tulipánová pole a různorodou evropskou krajinu',
                  quality: 'Nizozemské zpracování pro přesnost a kvalitu',
                },
                inStock: 'Skladem',
                lede: 'Traktor připravený pro nakladač na krmivo, seno, štěrk a zimní údržbu cest.',
                power: 'Výkon',
                price: 'Cena',
                variants: {
                  polderGreen: 'Polder Green',
                  tulipMagenta: 'Tulipánová magenta',
                },
              },
              role: 'rozhodování',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              title: 'Rozhodovací remote',
            },
            explore: {
              footer: {
                basedOn: 'založeno na',
                projectPrefix: 'projekt společnosti',
                projectSuffix: '',
                techstack: 'technologie',
              },
              header: {
                machines: 'Stroje',
                navigation: 'Hlavní navigace',
                stores: 'Prodejci',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              products: {
                all: 'Vše',
                autonomous: 'Autonomní',
                classics: 'Klasické',
                count: '{{count}} produktů',
                filter: 'Filtr',
                filterLabel: 'Filtr strojů',
                title: 'Všechny stroje',
              },
              recommendations: {
                aiFirst: 'AI varianta',
                bestRows: 'Nejlepší do úzkých řádků',
                loaderReady: 'Připraveno pro nakladač',
                title: 'Doporučení',
                vineyard: 'Profil pro vinice',
              },
              role: 'procházení',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              stores: {
                northRegion: 'Severní region',
                southRegion: 'Jižní region',
                title: 'Prodejci',
              },
              teasers: {
                autonomous: 'Autonomní traktory',
                classic: 'Klasické traktory',
              },
              title: 'Průzkumný remote',
            },
            shell: {
              boundaries: {
                checkout: 'pokladna',
                decide: 'rozhodování',
                explore: 'procházení',
                toggle: 'zobrazit hranice týmů',
              },
              hero: {
                eyebrow: 'Federovaný obchod s traktory',
                lede: 'Full-stack Micro Vertical ukázka, kde Procházení, Rozhodování a Pokladna vycházejí samostatně, ale skládají jeden obchod.',
                primary: 'Zobrazit Field Loader',
                secondary: 'Porovnat stroje',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              remotes: {
                checkout: 'Checkout remote',
                decide: 'Decide remote',
                explore: 'Explore remote',
              },
              routes: {
                cart: 'Košík',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Prodejci',
              },
              title: 'Acre & Iron',
            },
          },
          translation: {
            checkout: {
              actions: {
                addToCart: 'Přidat do košíku',
                checkout: 'Pokladna',
                continueShopping: 'Pokračovat v nákupu',
                remove: 'Odebrat',
                viewCart: 'Zobrazit košík',
              },
              cart: {
                empty: 'Košík je prázdný.',
                title: 'Košík',
                total: 'Celkem',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              product: {
                stockShipping: '8 skladem, doprava zdarma',
              },
              role: 'pokladna',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              title: 'Pokladní remote',
            },
            decide: {
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              product: {
                availability: 'Dostupnost',
                eyebrow: 'Detail stroje',
                features: {
                  comfort: 'Ergonomický návrh zaměřený na pohodlí a efektivitu obsluhy',
                  landscapes: 'Optimalizovaný pro tulipánová pole a různorodou evropskou krajinu',
                  quality: 'Nizozemské zpracování pro přesnost a kvalitu',
                },
                inStock: 'Skladem',
                lede: 'Traktor připravený pro nakladač na krmivo, seno, štěrk a zimní údržbu cest.',
                power: 'Výkon',
                price: 'Cena',
                variants: {
                  polderGreen: 'Polder Green',
                  tulipMagenta: 'Tulipánová magenta',
                },
              },
              role: 'rozhodování',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              title: 'Rozhodovací remote',
            },
            explore: {
              footer: {
                basedOn: 'založeno na',
                projectPrefix: 'projekt společnosti',
                projectSuffix: '',
                techstack: 'technologie',
              },
              header: {
                machines: 'Stroje',
                navigation: 'Hlavní navigace',
                stores: 'Prodejci',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              products: {
                all: 'Vše',
                autonomous: 'Autonomní',
                classics: 'Klasické',
                count: '{{count}} produktů',
                filter: 'Filtr',
                filterLabel: 'Filtr strojů',
                title: 'Všechny stroje',
              },
              recommendations: {
                aiFirst: 'AI varianta',
                bestRows: 'Nejlepší do úzkých řádků',
                loaderReady: 'Připraveno pro nakladač',
                title: 'Doporučení',
                vineyard: 'Profil pro vinice',
              },
              role: 'procházení',
              routes: {
                cart: 'Košík',
                checkout: 'Pokladna',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Výběr prodejce',
                thankYou: 'Potvrzení objednávky',
                unavailable: 'Nedostupné',
              },
              stores: {
                northRegion: 'Severní region',
                southRegion: 'Jižní region',
                title: 'Prodejci',
              },
              teasers: {
                autonomous: 'Autonomní traktory',
                classic: 'Klasické traktory',
              },
              title: 'Průzkumný remote',
            },
            shell: {
              boundaries: {
                checkout: 'pokladna',
                decide: 'rozhodování',
                explore: 'procházení',
                toggle: 'zobrazit hranice týmů',
              },
              hero: {
                eyebrow: 'Federovaný obchod s traktory',
                lede: 'Full-stack Micro Vertical ukázka, kde Procházení, Rozhodování a Pokladna vycházejí samostatně, ale skládají jeden obchod.',
                primary: 'Zobrazit Field Loader',
                secondary: 'Porovnat stroje',
              },
              language: {
                cs: 'Čeština',
                en: 'Angličtina',
                switcher: 'Jazyk',
              },
              remotes: {
                checkout: 'Checkout remote',
                decide: 'Decide remote',
                explore: 'Explore remote',
              },
              routes: {
                cart: 'Košík',
                home: 'Domů',
                listing: 'Traktory',
                productDetail: 'Detail traktoru',
                storePicker: 'Prodejci',
              },
              title: 'Acre & Iron',
            },
          },
        },
        en: {
          shell: {
            checkout: {
              actions: {
                addToCart: 'Add to basket',
                checkout: 'Checkout',
                continueShopping: 'Continue shopping',
                remove: 'Remove',
                viewCart: 'View cart',
              },
              cart: {
                empty: 'Your cart is empty.',
                title: 'Basket',
                total: 'Total',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              product: {
                stockShipping: '8 in stock, free shipping',
              },
              role: 'checkout',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              title: 'Checkout Vertical',
            },
            decide: {
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              product: {
                availability: 'Availability',
                eyebrow: 'Machine detail',
                features: {
                  comfort: 'Ergonomic design with a focus on operator comfort and efficiency',
                  landscapes: 'Optimized for tulip fields and versatile European landscapes',
                  quality: 'Dutch craftsmanship for precision and quality',
                },
                inStock: 'In stock',
                lede: 'A loader-ready tractor for feed, hay, gravel, and winter road work.',
                power: 'Power',
                price: 'Price',
                variants: {
                  polderGreen: 'Polder Green',
                  tulipMagenta: 'Tulip Magenta',
                },
              },
              role: 'decide',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              title: 'Decide Vertical',
            },
            explore: {
              footer: {
                basedOn: 'based on',
                projectPrefix: 'a',
                projectSuffix: 'project',
                techstack: 'techstack',
              },
              header: {
                machines: 'Machines',
                navigation: 'Main navigation',
                stores: 'Stores',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              products: {
                all: 'All',
                autonomous: 'Autonomous',
                classics: 'Classics',
                count: '{{count}} products',
                filter: 'Filter',
                filterLabel: 'Filter machines',
                title: 'All Machines',
              },
              recommendations: {
                aiFirst: 'AI-first option',
                bestRows: 'Best for tight rows',
                loaderReady: 'Loader-ready',
                title: 'Recommendations',
                vineyard: 'Vineyard profile',
              },
              role: 'explore',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              stores: {
                northRegion: 'North region',
                southRegion: 'South region',
                title: 'Stores',
              },
              teasers: {
                autonomous: 'Autonomous Tractors',
                classic: 'Classic Tractors',
              },
              title: 'Explore Vertical',
            },
            shell: {
              boundaries: {
                checkout: 'checkout',
                decide: 'decide',
                explore: 'explore',
                toggle: 'show team boundaries',
              },
              hero: {
                eyebrow: 'Federated tractor commerce',
                lede: 'A full-stack Micro Vertical reference where Explore, Decide, and Checkout ship independently but compose into one storefront.',
                primary: 'View Field Loader',
                secondary: 'Compare machines',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              remotes: {
                checkout: 'Checkout Vertical',
                decide: 'Decide Vertical',
                explore: 'Explore Vertical',
              },
              routes: {
                cart: 'Cart',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Stores',
              },
              title: 'Acre & Iron',
            },
          },
          translation: {
            checkout: {
              actions: {
                addToCart: 'Add to basket',
                checkout: 'Checkout',
                continueShopping: 'Continue shopping',
                remove: 'Remove',
                viewCart: 'View cart',
              },
              cart: {
                empty: 'Basket is empty.',
                title: 'Basket',
                total: 'Total',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              product: {
                stockShipping: '8 in stock, free shipping',
              },
              role: 'checkout',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              title: 'Checkout Vertical',
            },
            decide: {
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              product: {
                availability: 'Availability',
                eyebrow: 'Machine detail',
                features: {
                  comfort: 'Ergonomic design with a focus on operator comfort and efficiency',
                  landscapes: 'Optimized for tulip fields and versatile European landscapes',
                  quality: 'Dutch craftsmanship for precision and quality',
                },
                inStock: 'In stock',
                lede: 'A loader-ready tractor for feed, hay, gravel, and winter road work.',
                power: 'Power',
                price: 'Price',
                variants: {
                  polderGreen: 'Polder Green',
                  tulipMagenta: 'Tulip Magenta',
                },
              },
              role: 'decide',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              title: 'Decide Vertical',
            },
            explore: {
              footer: {
                basedOn: 'based on',
                projectPrefix: 'a',
                projectSuffix: 'project',
                techstack: 'techstack',
              },
              header: {
                machines: 'Machines',
                navigation: 'Main navigation',
                stores: 'Stores',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              products: {
                all: 'All',
                autonomous: 'Autonomous',
                classics: 'Classics',
                count: '{{count}} products',
                filter: 'Filter',
                filterLabel: 'Filter machines',
                title: 'All Machines',
              },
              recommendations: {
                aiFirst: 'AI-first option',
                bestRows: 'Best for tight rows',
                loaderReady: 'Loader-ready',
                title: 'Recommendations',
                vineyard: 'Vineyard profile',
              },
              role: 'explore',
              routes: {
                cart: 'Cart',
                checkout: 'Checkout',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Store picker',
                thankYou: 'Order confirmation',
                unavailable: 'Unavailable',
              },
              stores: {
                northRegion: 'North region',
                southRegion: 'South region',
                title: 'Stores',
              },
              teasers: {
                autonomous: 'Autonomous Tractors',
                classic: 'Classic Tractors',
              },
              title: 'Explore Vertical',
            },
            shell: {
              boundaries: {
                checkout: 'checkout',
                decide: 'decide',
                explore: 'explore',
                toggle: 'show team boundaries',
              },
              hero: {
                eyebrow: 'Federated tractor commerce',
                lede: 'A full-stack Micro Vertical reference where Explore, Decide, and Checkout ship independently but compose into one storefront.',
                primary: 'View Field Loader',
                secondary: 'Compare machines',
              },
              language: {
                cs: 'Czech',
                en: 'English',
                switcher: 'Language',
              },
              remotes: {
                checkout: 'Checkout Vertical',
                decide: 'Decide Vertical',
                explore: 'Explore Vertical',
              },
              routes: {
                cart: 'Cart',
                home: 'Home',
                listing: 'Tractors',
                productDetail: 'Tractor detail',
                storePicker: 'Stores',
              },
              title: 'Acre & Iron',
            },
          },
        },
      } as unknown as Record<string, Record<string, string>>,
      supportedLngs: ['en', 'cs'],
    },
  },
  router: {
    framework: 'tanstack',
  },
});
