// @generated by @modern-js/create.
// Author route metadata in colocated src/routes/**/route.meta.ts files.
// This compatibility manifest is regenerated from route-owned metadata.

export const ultramodernRouteNamespace = 'checkout' as const;

export const ultramodernRouteMetadata = [
  {
    canonicalPath: '/',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-home',
    indexable: false,
    localisedPaths: {
      cs: '/',
      en: '/',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.title',
  },
  {
    canonicalPath: '/cart',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-cart',
    indexable: false,
    localisedPaths: {
      cs: '/kosik',
      en: '/cart',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.cart',
  },
  {
    canonicalPath: '/checkout',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-start',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna',
      en: '/checkout',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.checkout',
  },
  {
    canonicalPath: '/checkout/thank-you',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-thank-you-parent',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna/dekujeme',
      en: '/checkout/thank-you',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.thankYou',
  },
  {
    canonicalPath: '/checkout/thank-you/:orderId?',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-thank-you',
    indexable: false,
    localisedPaths: {
      cs: '/pokladna/dekujeme/:orderId?',
      en: '/checkout/thank-you/:orderId?',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.thankYou',
  },
  {
    canonicalPath: '/unavailable',
    descriptionKey: 'checkout.seo.description',
    id: 'checkout-unavailable',
    indexable: false,
    localisedPaths: {
      cs: '/nedostupne',
      en: '/unavailable',
    },
    mfBoundaryId: 'verticalCheckout',
    namespace: 'checkout',
    ownerAppId: 'checkout',
    public: false,
    publicSurface: 'private-app-screen',
    titleKey: 'checkout.routes.unavailable',
  },
] as const;

export const ultramodernLocalisedUrls = {
  '/cart': {
    cs: '/kosik',
    en: '/cart',
  },
  '/checkout': {
    cs: '/pokladna',
    en: '/checkout',
  },
  '/checkout/thank-you': {
    cs: '/pokladna/dekujeme',
    en: '/checkout/thank-you',
  },
  '/checkout/thank-you/:orderId?': {
    cs: '/pokladna/dekujeme/:orderId?',
    en: '/checkout/thank-you/:orderId?',
  },
  '/kosik': {
    cs: '/kosik',
    en: '/cart',
  },
  '/nedostupne': {
    cs: '/nedostupne',
    en: '/unavailable',
  },
  '/pokladna': {
    cs: '/pokladna',
    en: '/checkout',
  },
  '/pokladna/dekujeme': {
    cs: '/pokladna/dekujeme',
    en: '/checkout/thank-you',
  },
  '/pokladna/dekujeme/:orderId?': {
    cs: '/pokladna/dekujeme/:orderId?',
    en: '/checkout/thank-you/:orderId?',
  },
  '/unavailable': {
    cs: '/nedostupne',
    en: '/unavailable',
  },
} as const;

export const ultramodernPublicRoutes = [] as const;

export const ultramodernRouteConfig = {
  authoring: 'colocated-route-meta',
  generatedManifest: true,
  localisedUrls: ultramodernLocalisedUrls,
  namespace: ultramodernRouteNamespace,
  publicRoutes: ultramodernPublicRoutes,
  routes: ultramodernRouteMetadata,
  source: 'route-owned',
} as const;
